### ISSUE TITLE
Octanify the codebase

### ISSUE THREAD

**Issue by bertdeblock** [Bagaar/ember-breadcrumbs#15]

**Comment by Windvis** [comment]
Any idea what impact that has on the Ember versions we can support?

**Comment by Windvis** [comment]
I guess we could support Ember 3.4+ with these polyfills:
- https://github.com/pzuraq/ember-native-class-polyfill
- https://github.com/pzuraq/ember-decorators-polyfill

**Comment by BnitoBzh** [comment]
Can you release a new version ? like 1.0.0 ?

**Comment by cah-briangantzler** [comment]
Is this addon still being maintained? I like the use of HBS to define the breadcrumb

**Comment by bertdeblock** [comment]
@cah-briangantzler We still use it yes. It just hasn't been high on my to-do list. I'll try to finish up #40 and cut a new release.
