### ISSUE TITLE
Remove the bgr prefix from the component names

### ISSUE THREAD

**Issue by Windvis** [Bagaar/ember-breadcrumbs#2]
I don't think the components need to be prefixed, right? Although I'm not sure what the best practise is for naming addon components.

**Comment by NindroidX** [comment]
Nevermind. Not compatible with Ember < 3.4 and classic component invocation.

**Comment by Windvis** [comment]
Since there is an AngleBrackets polyfill I think it might be a good idea to drop the prefix anyway.
