### ISSUE TITLE
Consider deprecating this addon in favour of `ember-breadcrumb-trail`

### ISSUE THREAD

**Issue by bertdeblock** [Bagaar/ember-breadcrumbs#57]
Motivation:

- [ember-breadcrumb-trail](https://github.com/Windvis/ember-breadcrumb-trail) also uses a template-based approach
- `ember-breadcrumb-trail` supports FastBoot, this addon does not (because of the modifier + `in-element` approach)
- `ember-breadcrumb-trail` is more flexible since it's completely helper based
- It's better to "join forces" than to have multiple addons trying to solve the same problem (in a similar way in this case)

**Comment by MichalBryxi** [comment]
Just updating my app to `ember-source > 4.x.x.` and bumped into this addon not being compatible. So I'm curious what would be the recommendation.

**Comment by bertdeblock** [comment]
v2 of `@bagaar/ember-breadcrumbs` is now compatible with Ember v4, but it might still be the case that I deprecate this addon at some point. Feedback/thoughts about this are appreciated of course!

**Comment by MichalBryxi** [comment]
That's a hrad one. I do want it only as a user - install, configure, forget about it. So as long as it works, I don't really care which one am I using. I created experimental branch to try `ember-breadcrumb-trail` and whether I will see any benefits there.

So far it seems that it has the same capabilities?

**Comment by villander** [comment]
@bertdeblock and how about the Ember Engines support on `ember-breadcrumb-trail`?

**Comment by bertdeblock** [comment]
Pretty sure it's also compatible with engines, even though it's not explicitly mentioned in the README.
The setup is probably very similar to this addon:
- Make `ember-breadcrumb-trail` a dependency of both the host app and the engine(s)
- Define the `breadcrumbs` service as a dependency that the host app needs to provide to the engine(s)
- Use the `breadcrumb` and `breadcrumbs` helpers within the engine(s)

**Comment by bertdeblock** [comment]
Closing for now.
